image: docker:git
services:
  - docker:dind

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - release
  - deploy

release:
  stage: release
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker stop discord-bot
    - docker rm discord-bot
    - docker run -d --name discord-bot $CI_REGISTRY_IMAGE:latest
  only:
    - master
